### ISSUE TITLE
Use chrome.commands api

### ISSUE THREAD

**Issue by fregante** [first1apps/chrome-extensions#2]
Chrome supports native keyboard shortcuts [commands](https://developer.chrome.com/extensions/commands). Most of this plugin can probably be replaced with a default command in the `manifest.json` file and this:

``` js
chrome.commands.onCommand.addListener(function(command) {
  if (command === 'debugger') {
    debugger;
  }
});
```

UI is also unneeded since Chrome has its own UI to customize shortcuts:

![Chrome keyboard UI](http://www.howtogeek.com/wp-content/uploads/2012/10/650x500ximage217.png.pagespeed.gp+jp+jw+pj+js+rj+rp+rw+ri+cp+md.ic.0onrNxYmDZ.png)

Would you accept a PR?

**Comment by first1apps** [comment]
Thanks for the info @bfred-it . I'll accept a pull request if you made one and publish it to the Chrome store.
